---
title: "Randomized Controlled Trials"
---

::: callout-note
:::
```{r, echo=TRUE}

abtest_data<-readRDS("C:/Users/mouni/Downloads/Causal_Data_Science_Data/Causal_Data_Science_Data/abtest_online.rds")
```

1.)
```{r, echo=TRUE}

library(ggplot2)

compare_previous_visit<-ggplot(abtest_data, aes(x = chatbot, y = previous_visit, color = as.factor(chatbot))) +
  geom_boxplot() +
  labs(title = "Covariate Balance Check",
       x = "Chatbot (False = Control, True = Treatment)",
       y = "Previous Visit")
compare_mobiledevice<-ggplot(abtest_data, aes(x = chatbot, y = mobile_device, color = as.factor(chatbot))) +
  geom_boxplot() +
  labs(title = "Covariate Balance Check",
       x = "Chatbot (False = Control, True = Treatment)",
       y = "Mobile Device")
compare_purchase<-ggplot(abtest_data, aes(x = chatbot, y = purchase_amount, color = as.factor(chatbot))) +
  geom_boxplot() +
  labs(title = "Covariate Balance Check",
       x = "Chatbot (False = Control, True = Treatment)",
       y = "Purchase amount")
compare_previous_visit
compare_mobiledevice
compare_purchase
```


2.)
```{r, echo=TRUE}

model<-lm(purchase_amount~chatbot+previous_visit+mobile_device,data=abtest_data)
summary(model)
```
3.)
```{r, echo=TRUE}

model_sub<-lm(purchase_amount~chatbot*mobile_device + chatbot*previous_visit,data=abtest_data)
summary(model_sub)
```

4.)
```{r, echo=TRUE}

logistic_model<-glm(purchase~chatbot+previous_visit+mobile_device,data=abtest_data,family="binomial")
summary(logistic_model)
```
