{
  "hash": "b821a452098e6df9aa32672c1030180c",
  "result": {
    "markdown": "---\ntitle: \"Directed Acyclic Graphs\"\n---\n\n\n::: callout-note\n:::\n\n1.)\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-1_2c7dbe9078fba4dd0793250beb6e3748'}\n\n```{.r .cell-code}\ncustomer_data<-readRDS(\"C:/Users/mouni/Downloads/Causal_Data_Science_Data/Causal_Data_Science_Data/customer_sat.rds\")\n\nlibrary(dagitty)\n\ndag <- dagitty('dag {\n  location -> parking_spot\n  parking_spot -> sales\n}')\ncoords = list(x = c(Y = 3, Z = 2, X = 1),\n                y = c(Y = 0, Z = 0, X = 0))\nplot(dag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Plot coordinates for graph not supplied! Generating coordinates, see ?coordinates for how to set your own.\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n2.)\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-2_c3b68690daeea335ea3f4bd5aa5f3d09'}\n\n```{.r .cell-code}\ncustomer_data<-readRDS(\"C:/Users/mouni/Downloads/Causal_Data_Science_Data/Causal_Data_Science_Data/customer_sat.rds\")\n\n       \nmodel1<-lm(satisfaction~follow_ups,data=customer_data)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups, data = customer_data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -12.412  -5.257   1.733   4.506  12.588 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  78.8860     4.2717  18.467 1.04e-10 ***\n#> follow_ups   -3.3093     0.6618  -5.001 0.000243 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 7.923 on 13 degrees of freedom\n#> Multiple R-squared:  0.658,\tAdjusted R-squared:  0.6316 \n#> F-statistic: 25.01 on 1 and 13 DF,  p-value: 0.0002427\n```\n:::\n\n```{.r .cell-code}\nmodel2<-lm(satisfaction~follow_ups+subscription,data=customer_data)\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = satisfaction ~ follow_ups + subscription, data = customer_data)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -4.3222 -2.1972  0.3167  2.2667  3.9944 \n#> \n#> Coefficients:\n#>                      Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)           26.7667     6.6804   4.007  0.00206 ** \n#> follow_ups             2.1944     0.7795   2.815  0.01682 *  \n#> subscriptionPremium   44.7222     5.6213   7.956 6.88e-06 ***\n#> subscriptionPremium+  18.0722     2.1659   8.344 4.37e-06 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 2.958 on 11 degrees of freedom\n#> Multiple R-squared:  0.9597,\tAdjusted R-squared:  0.9487 \n#> F-statistic: 87.21 on 3 and 11 DF,  p-value: 5.956e-08\n```\n:::\n\n```{.r .cell-code}\ncoef_comp<-cbind(T1=coef(model1),T2=coef(model2))\nprint(coef_comp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>                             T1        T2\n#> (Intercept)          78.886047 26.766667\n#> follow_ups           -3.309302  2.194444\n#> subscriptionPremium  78.886047 44.722222\n#> subscriptionPremium+ -3.309302 18.072222\n```\n:::\n:::\n\n\n3.)\nComparison:\nIntercept:\nIn Model 1, the intercept is 78.8860.\nIn Model 2, when accounting for subscription, the intercept decreases significantly to 26.7667.\n\nfollow_ups:\nIn Model 1, the coefficient for follow_ups is -3.3093.\nIn Model 2, when accounting for subscription, the coefficient for follow_ups becomes 2.1944.\n\nsubscription:\nThe coefficients for both subscription levels(premium and premium+) are positive and statistically significant.\n\nThe significant decrease in the intercept possibly says that, on average, satisfaction is lower when considering the impact of subscription levels.\n\nThe change in the coefficient for follow_ups suggests that the relationship between follow-up calls and satisfaction is positive as it changed from (-3.3093 to 2.1944) when accounting for subscription levels. This could indicate that the effect of follow-up calls on satisfaction depends on the subscription level.\n\nHigher subscription levels, Premium and Premium+, are associated with significantly higher satisfaction. The decrease in the intercept suggests that the baseline satisfaction is lower when considering subscription levels.\n\n\n4.)\n\n::: {.cell hash='05_dag_cache/html/unnamed-chunk-3_d15f4c68a284bcd55479f65f891654c4'}\n\n```{.r .cell-code}\nlibrary(dagitty)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n#> ✔ dplyr     1.1.4     ✔ readr     2.1.4\n#> ✔ forcats   1.0.0     ✔ stringr   1.5.1\n#> ✔ ggplot2   3.4.4     ✔ tibble    3.2.1\n#> ✔ lubridate 1.9.3     ✔ tidyr     1.3.0\n#> ✔ purrr     1.0.2     \n#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n#> ✖ dplyr::filter() masks stats::filter()\n#> ✖ dplyr::lag()    masks stats::lag()\n#> ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\ndata <- dagitty('dag {\n  follow_ups -> satisfaction\n  subscription -> follow_ups\n  subscription -> satisfaction\n}')\n\n  coordinates(dag) <- list(x = c(subscription = 3, follow_ups = 2, satisfaction = 1), y = c(subscription = 0, follow_ups = 1, satisfaction = 0))\n  #label <- data.frame(x = c(2, 2, 3), y = c(1, 2, 2), label = c(\"b1\", \"b2\", \"b3\"))\n  plot(data, main = \"Directed Acyclic Graph (DAG) for Relationship Analysis\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Plot coordinates for graph not supplied! Generating coordinates, see ?coordinates for how to set your own.\n```\n:::\n\n::: {.cell-output-display}\n![](05_dag_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Plot DAG\nlibrary(ggdag)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attaching package: 'ggdag'\n#> \n#> The following object is masked from 'package:stats':\n#> \n#>     filter\n```\n:::\n:::\n\n  \n\n\ndata<-readRDS(\"C:/Users/mouni/Downloads/Causal_Data_Science_Data/Causal_Data_Science_Data/customer_sat.rds\")\nn <- 1e+03\n\n# draw and create variables with specific dependencies\nsubscription <- rnorm(n)\nfollow_ups <- rnorm(n) \nsatisfaction <- rnorm(n)\n\n# rescale to realistic values\nsatisfaction <- sample(20:80,1) + scales::rescale(satisfaction, to = c(0, 80))\nfollow_ups <- scales::rescale(follow_ups, to = c(0, 10))\nsubscription <- factor(subscription, labels = c(\"Premium+\", \"Premium\"))\n\n# create tibble\ndf <- tibble(\n  satisfaction,\n  follow_ups,\n  subscription\n)\n\n# Not conditioning on education\nsimps_not_cond <- ggplot(df, aes(x = follow_ups, y = satisfaction)) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F)\n\n# Conditioning on education  \nsimps_cond <- ggplot(df, aes(x = follow_ups, y = satisfaction, color = subscription)) +\n  geom_point(alpha = .8) +\n  stat_smooth(method = \"lm\", se = F) +\n  theme(legend.position = \"right\")\n\n# Plot both plots\nsimps_not_cond\nsimps_cond\n\n  \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}